export const rootModuleType = 'ZRE network observer'
export const zreModuleType = 'ZRE node'
export const zreNodeModuleIdPrefix = 'ZRE-node:'
export const whisperMethodName = 'ZRE.whisper'
export const shoutMethodName = 'ZRE.shout'
export const restartMethodName = 'ZRE.restart'